name: Maven Compile
on:
    push:
        branches: [master]
    pull_request:
        branches-ignore: [l10n_master]
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                java: ['17']
        name: Java (Temurin) ${{ matrix.java }}
        steps:
            - uses: actions/checkout@v2
            - name: Set up Eclipse Temurin
              uses: actions/setup-java@v2
              with:
                  distribution: 'temurin'
                  java-version: ${{ matrix.java }}
                  java-package: jdk
                  cache: 'maven'

            # 4. Build via Maven 
            - name: Build via Maven
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: mvn clean package -P no-apidoc

            # 4b. Staging Jar Directories
            - name: Staging Jar Directories
              run: mkdir staging && cp target/*.jar staging

            # 4c. Staging Jars
            - name: Staging Jars
              uses: actions/upload-artifact@v2
              with:
                  name: Package
                  path: staging
